- name: Install other apps
  become: true
  ansible.builtin.apt:
    name:
      - filezilla
      - gimp
      - gpick
      - inkscape
      - jxplorer
      - keepassxc
      - meld
      - octave
      - pavucontrol
      - simple-scan
