homebrew_prefix: /home/linuxbrew/.linuxbrew

apt_install_packages:
  # --- homebrew ---
  - build-essential
  - procps
  - curl
  - file
  - git
  - zlib1g-dev
  # --- containers ---
  - docker.io
  - docker-compose
  - uidmap
  # --- tlp ---
  - tlp
  # --- flatpak ---
  - flatpak
  # --- gnome ---
  - gnome-tweaks
  - network-manager-openconnect-gnome
  - network-manager-vpnc-gnome
  # --- chrome ---
  - google-chrome-stable
  # --- teams ---
  # TODO remove once PWA is available
  - teams
  # --- pano ---
  - gir1.2-gda-5.0
  - gir1.2-gsound-1.0

apt_purge_packages:
  - power-profiles-daemon
  - snapd
  - systemd-oomd
  - unattended-upgrades

brew_install_packages:
  - dawidd6/tap/deber
  - dawidd6/tap/podman
  - dawidd6/tap/sshpass
  - ansible
  - ansible-lint
  - bat
  - cpio
  - curl
  - diff-so-fancy
  - diffoscope
  - distrobox
  - docker-completion
  - dos2unix
  - fish
  - fzf
  - gh
  - ghorg
  - git
  - gitbatch
  - go
  - htop
  - ipcalc
  - jfrog-cli
  - jq
  - lab
  - lm-sensors
  - ncdu
  - neofetch
  - neovim
  - nmap
  - node
  - parallel
  - python
  - rpm2cpio
  - ruby
  - shellcheck
  - strace
  - stress
  - trash-cli
  - tree
  - xsel

flatpak_install_packages:
  - com.visualstudio.code
  - com.spotify.Client
  - com.mattjakeman.ExtensionManager
  - org.filezillaproject.Filezilla
  - org.gimp.GIMP
  - org.kryogenix.Pick
  - org.inkscape.Inkscape
  - org.pulseaudio.pavucontrol
  - org.keepassxc.KeePassXC
  - org.gnome.Boxes
