- name: repo fish
  become: yes
  apt_repository:
    repo: ppa:fish-shell/release-3

- name: install fish
  become: yes
  apt:
    name: fish

- name: use fish
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/fish
