- name: Install git and deps
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name:
      - diff-so-fancy
      - git

- name: Purge git
  become: true
  ansible.builtin.apt:
    state: absent
    purge: true
    autoremove: true
    name: git
