---
- name: Set up OS
  hosts: localhost
  vars:
    homebrew_prefix: /home/linuxbrew/.linuxbrew
    apt_packages:
      # --- homebrew ---
      - build-essential
      - procps
      - curl
      - file
      - git
      - zlib1g-dev
      # --- containers ---
      - uidmap
      # --- gnome ---
      - gnome-clocks
      - gnome-tweaks
      - gnome-weather
      - gnome-shell-extension-manager
      - network-manager-openconnect-gnome
      - network-manager-vpnc-gnome
      - python3-pydrive # for deja-dup
      # --- chrome ---
      - google-chrome-stable
      # --- other ---
      - copyq
      - filezilla
      - gimp
      - gpick
      - inkscape
      - keepassxc
      - pavucontrol
      - virt-manager
    snap_packages:
      - code:classic
      - spotify
    homebrew_formulae:
      - dawidd6/tap/sshpass
      - ansible
      - ansible-lint
      - bat
      - btop
      - cpio
      - curl
      - diff-so-fancy
      - diffoscope
      - distrobox
      - dos2unix
      - fish
      - fzf
      - gh
      - ghorg
      - git
      - gitbatch
      - glab
      - go
      - grex
      - htop
      - ipcalc
      - jfrog-cli
      - jq
      - lab
      - lm-sensors
      - ncdu
      - neofetch
      - neovim
      - nmap
      - node
      - noti
      - parallel
      - podman
      - python
      - rclone
      - rpm2cpio
      - ruby
      - shellcheck
      - strace
      - stress
      - tealdeer
      - trash-cli
      - tree
      - xsel
  handlers:
    - name: Checkout dotfiles
      ansible.builtin.command: "git --git-dir={{ ansible_env.HOME }}/.dotfiles --work-tree={{ ansible_env.HOME }} checkout -f"
      args:
        warn: false
  tasks:
    - name: Apt-related
      tags:
        - apt
      block:
        - name: Add chrome repo key
          become: true
          ansible.builtin.apt_key:
            url: https://dl.google.com/linux/linux_signing_key.pub

        - name: Add chrome repo
          become: true
          ansible.builtin.lineinfile:
            line: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
            path: /etc/apt/sources.list.d/google-chrome.list
            regexp: deb
            create: true
            mode: 0644

        - name: Install apt packages
          become: true
          ansible.builtin.apt:
            update_cache: true
            name: "{{ apt_packages }}"

    - name: Homebrew-related
      tags:
        - homebrew
      block:
        - name: Create Homebrew base directories
          become: true
          ansible.builtin.file:
            path: "{{ homebrew_prefix }}/bin"
            state: directory
            owner: "{{ ansible_env.USER }}"
            group: "{{ ansible_env.USER }}"
            mode: 0755

        - name: Clone Homebrew repository
          ansible.builtin.git:
            repo: https://github.com/Homebrew/brew
            dest: "{{ homebrew_prefix }}/Homebrew"
            update: false
            version: master

        - name: Create symlink to brew binary
          ansible.builtin.file:
            src: "{{ homebrew_prefix }}/Homebrew/bin/brew"
            dest: "{{ homebrew_prefix }}/bin/brew"
            state: link

        - name: Install Homebrew formulae
          environment:
            HOMEBREW_DEVELOPER: 1
            HOMEBREW_NO_AUTO_UPDATE: 1
            HOMEBREW_NO_INSTALL_FROM_API: 1
          ansible.builtin.shell: "ulimit -Sn 100000; {{ homebrew_prefix }}/bin/brew install {{ homebrew_formulae | join(' ') }}"
          register: brew_install
          changed_when: '"Pouring" in brew_install.stdout'

        - name: Set fish as default shell
          become: true
          ansible.builtin.user:
            name: "{{ ansible_env.USER }}"
            shell: "{{ homebrew_prefix }}/bin/fish"

    - name: Snap-related
      tags:
        - snap
      block:
        - name: Install snap packages
          become: true
          community.general.snap:
            name: "{{ item | replace(':classic', '') }}"
            classic: "{{ true if ':classic' in item else false }}"
          loop: "{{ snap_packages }}"

    - name: Dotfiles-related
      tags:
        - dotfiles
      block:
        - name: Clone dotfiles
          ansible.builtin.git:
            repo: https://github.com/dawidd6/dotfiles.git
            dest: "{{ ansible_env.HOME }}/.dotfiles"
            update: false
            bare: true
            version: master
          notify: Checkout dotfiles

        - name: Do not show untracked dotfiles
          community.general.git_config:
            repo: "{{ ansible_env.HOME }}/.dotfiles"
            name: status.showUntrackedFiles
            value: "no"
            scope: local

        - name: Set dotfiles fetch config
          community.general.git_config:
            repo: "{{ ansible_env.HOME }}/.dotfiles"
            name: remote.origin.fetch
            value: "+refs/heads/*:refs/remotes/origin/*"
            scope: local

    - name: Deploy scripts
      tags:
        - scripts
      ansible.builtin.git:
        repo: https://github.com/dawidd6/bin.git
        dest: "{{ ansible_env.HOME }}/bin"
        update: false
        version: master

    - name: Tweak GNOME settings
      tags:
        - gnome
      ansible.builtin.command: gsettings set '{{ item.schema }}' '{{ item.key }}' '{{ item.value }}'
      changed_when: true
      loop:
        - schema: org.gnome.desktop.interface
          key: gtk-theme
          value: "Yaru-dark"
        - schema: org.gnome.desktop.interface
          key: show-battery-percentage
          value: "true"
        - schema: org.gnome.desktop.interface
          key: clock-show-seconds
          value: "true"
        - schema: org.gnome.desktop.interface
          key: clock-show-date
          value: "true"
        - schema: org.gnome.desktop.interface
          key: clock-show-weekday
          value: "true"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: audible-bell
          value: "false"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: use-theme-colors
          value: "false"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: foreground-color
          value: "#FFFFFF"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: background-color
          value: "#181818"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: scrollbar-policy
          value: "always"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: scrollback-unlimited
          value: "false"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: scrollback-lines
          value: "10000"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: default-size-columns
          value: "140"
        - schema: org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/
          key: default-size-rows
          value: "40"
        - schema: org.gnome.Terminal.Legacy.Settings
          key: theme-variant
          value: "dark"
        - schema: org.gnome.Terminal.Legacy.Settings
          key: new-tab-position
          value: "next"
