- name: Install basic stuff
  hosts: localhost
  roles:
    - { role: brew, tags: brew }
    - { role: apps, tags: apps }
    - { role: fish, tags: fish }
    - { role: chrome, tags: chrome }
    - { role: spotify, tags: spotify }

- name: Install power management stuff
  hosts: localhost
  roles:
    - { role: tlp, tags: tlp }

- name: Install work stuff
  hosts: localhost
  roles:
    - { role: teams, tags: teams }
    - { role: vpn, tags: vpn }

- name: Install development stuff
  hosts: localhost
  roles:
    - { role: docker, tags: docker }
    - { role: flutter, tags: flutter }
    - { role: golang, tags: golang }
    - { role: python, tags: python }
    - { role: ruby, tags: ruby }
    - { role: vscode, tags: vscode }

- name: Remove unneeded stuff
  hosts: localhost
  roles:
    - { role: snapd, tags: snapd }

- name: Deploy git repositories
  hosts: localhost
  roles:
    - { role: keys, tags: keys }
    - { role: dotfiles, tags: dotfiles }
    - { role: scripts, tags: scripts }
