- name: purge upgrading packages
  become: yes
  apt:
    state: absent
    purge: yes
    autoremove: yes
    name:
      - unattended-upgrades

- name: disable apt daily service
  become: yes
  systemd:
    name: "{{ item }}"
    masked: yes
    enabled: no
  with_items:
    - apt-daily-upgrade.service
    - apt-daily-upgrade.timer
    - apt-daily.service
    - apt-daily.timer
