- name: add keys
  become: yes
  apt_key:
    url: "{{ item }}"
  loop:
    - https://dl.google.com/linux/linux_signing_key.pub
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg

- name: add repos
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename | default(omit) }}"
  loop:
    - repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
      filename: google-chrome
    - repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      filename: vscode
    - repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
      filename: teams
    - repo: deb http://repository.spotify.com stable non-free
      filename: spotify
    - repo: ppa:fish-shell/release-3

- name: install apps
  become: yes
  apt:
    update_cache: yes
    name:
      - alien
      - cheese
      - chrome-gnome-shell
      - code
      - docker.io
      - evince
      - filezilla
      - firefox
      - fish
      - fonts-dejavu-extra
      - fonts-firacode
      - fonts-noto-color-emoji
      - gimp
      - gnome-boxes
      - gnome-calculator
      - gnome-calendar
      - gnome-clocks
      - gnome-system-monitor
      - gnome-tweaks
      - gnome-weather
      - google-chrome-stable
      - gpick
      - inkscape
      - jxplorer
      - keepassxc
      - meld
      - network-manager-openconnect-gnome
      - network-manager-vpnc-gnome
      - pavucontrol
      - octave
      - simple-scan
      - spotify-client
      - sshpass
      - teams
      - tlp
      - totem
      - traceroute
      - transmission
      - virtualbox

- name: purge unneeded packages
  become: yes
  apt:
    state: absent
    purge: yes
    autoremove: yes
    name:
      - snapd
      - unattended-upgrades

- name: set user shell
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    shell: "/usr/bin/fish"
