- name: remove default pi user
  become: yes
  user:
    name: pi
    state: absent
    remove: yes

- name: add my user
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    state: present
    shell: /bin/bash
    append: yes
    groups: adm,dialout,sudo,audio,video,plugdev,games,users,input,netdev
