- name: clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/dawidd6/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: false
    bare: true
    version: master
  notify: checkout dotfiles

- name: do not show untracked dotfiles
  community.general.git_config:
    repo: "{{ ansible_env.HOME }}/.dotfiles"
    name: "status.showUntrackedFiles"
    value: "no"
    scope: local

- name: set dotfiles fetch config
  community.general.git_config:
    repo: "{{ ansible_env.HOME }}/.dotfiles"
    name: "remote.origin.fetch"
    value: "+refs/heads/*:refs/remotes/origin/*"
    scope: local
