- name: clone dotfiles
  git:
    repo: git@github.com:dawidd6/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    accept_hostkey: yes
    update: no
    bare: yes
    version: master
  notify: checkout dotfiles

- name: do not show untracked dotfiles
  git_config:
    repo: "{{ ansible_env.HOME }}/.dotfiles"
    name: "status.showUntrackedFiles"
    value: "no"
    scope: local

- name: set dotfiles fetch config
  git_config:
    repo: "{{ ansible_env.HOME }}/.dotfiles"
    name: "remote.origin.fetch"
    value: "+refs/heads/*:refs/remotes/origin/*"
    scope: local
