- hosts: all
  become: yes
  tasks:
    - name: add spotify repo
      block:
        - apt_key:
            keyserver: hkp://keyserver.ubuntu.com:80
            id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
        - apt_repository:
            repo: deb http://repository.spotify.com stable non-free
            state: present

    - name: add virtualbox repo
      block:
        - apt_key:
            url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
            id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
        - apt_repository:
            repo: deb https://download.virtualbox.org/virtualbox/debian stretch contrib
            state: present

    - name: add docker repo
      block:
        - apt_key:
            url: https://download.docker.com/linux/debian/gpg
            id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        - apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
            state: present
