- name: Install GNOME apps
  become: true
  ansible.builtin.apt:
    name:
      - cheese
      - evince
      - gnome-boxes
      - gnome-calculator
      - gnome-calendar
      - gnome-clocks
      - gnome-shell-extension-prefs
      - gnome-system-monitor
      - gnome-tweaks
      - gnome-weather
      - network-manager-openconnect-gnome
      - network-manager-vpnc-gnome
      - transmission

- name: Install other apps
  become: true
  ansible.builtin.apt:
    name:
      - filezilla
      - gimp
      - gpick
      - inkscape
      - jxplorer
      - keepassxc
      - meld
      - octave
      - pavucontrol
      - simple-scan
