- name: create brew base directories
  become: true
  file:
    path: "{{ brew }}/bin"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: clone brew repository
  git:
    repo: "https://github.com/Homebrew/brew"
    dest: "{{ brew }}/Homebrew"
    update: no
    version: "master"

- name: create symlink to brew binary
  file:
    src: "{{ brew }}/Homebrew/bin/brew"
    dest: "{{ brew }}/bin/brew"
    state: "link"
  notify: brew update

- name: install brew packages
  homebrew:
    path: "{{ brew }}/bin"
    name: "{{ brew_packages }}"

- name: unlink brewed dpkg
  homebrew:
    state: unlinked
    path: "{{ brew }}/bin"
    name: dpkg

- name: add brewed fish to shells
  become: yes
  lineinfile:
    path: /etc/shells
    line: "{{ brew }}/bin/fish"

- name: set fish as default shell
  become: yes
  user:
    name: "{{ user }}"
    shell: "{{ brew }}/bin/fish"
