- name: key code
  become: yes
  apt_key:
    url: "{{ code_key }}"

- name: repo code
  become: yes
  apt_repository:
    repo: "{{ code_repo }}"
    state: present
    filename: vscode # postinst script installs this file if does not exist

- name: install code
  become: yes
  apt:
    name: "{{ code_package }}"

- name: list code extensions
  command: "code --list-extensions"
  register: code_installed_extensions
  changed_when: false

- name: install code extensions
  command: code --install-extension "{{ item }}"
  when: item not in code_installed_extensions.stdout
  with_items: "{{ code_extensions }}"

- name: uninstall code extensions
  command: code --uninstall-extension "{{ item }}"
  when: item not in code_extensions
  with_items: "{{ code_installed_extensions.stdout_lines }}"
