- name: key docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: repo docker
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install docker
  become: yes
  apt:
    name: docker-ce

- name: add user to docker group
  become: yes
  user:
    name: "{{ user }}"
    append: yes
    groups:
      - docker
