- name: clone dotfiles
  git:
    repo: git@github.com:dawidd6/dotfiles.git
    dest: "{{ dotfiles }}"
    accept_hostkey: yes
    update: no
    bare: yes
    version: master

- name: do not show untracked dotfiles
  git_config:
    repo: "{{ dotfiles }}"
    name: "status.showUntrackedFiles"
    value: "no"
    scope: local

- name: set dotfiles fetch config
  git_config:
    repo: "{{ dotfiles }}"
    name: "remote.origin.fetch"
    value: "+refs/heads/*:refs/remotes/origin/*"
    scope: local

- name: checkout dotfiles
  command: git --git-dir="{{ dotfiles }}" --work-tree="{{ home }}" checkout -f
  args:
    creates: "{{ home }}/README.md"
    warn: false
