- import_tasks: packages.yml
  tags: packages

- import_tasks: dconf.yml
  tags: dconf

- import_tasks: printer.yml
  tags: printer

- import_tasks: intellij.yml
  tags: intellij

- import_tasks: keys.yml
  tags: keys
- import_tasks: scripts.yml
  tags: scripts
- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: salsa.yml
  tags: salsa
- import_tasks: github.yml
  tags: github

- import_tasks: tlp.yml
  when: ansible_system_vendor == "LENOVO" # laptop
  tags: tlp
- import_tasks: go.yml
  tags: go
- import_tasks: fish.yml
  tags: fish
- import_tasks: code.yml
  tags: code
- import_tasks: docker.yml
  tags: docker
- import_tasks: spotify.yml
  tags: spotify
