- import_tasks: apt.yml
  tags: apt
- import_tasks: brew.yml
  tags: brew
- import_tasks: code.yml
  tags: code
- import_tasks: docker.yml
  tags: docker
- import_tasks: intellij.yml
  tags: intellij
- import_tasks: printer.yml
  tags: printer
- import_tasks: spotify.yml
  tags: spotify
- import_tasks: tlp.yml
  tags: tlp
  when: ansible_system_vendor == "LENOVO" # laptop

- import_tasks: keys.yml
  tags: keys
- import_tasks: scripts.yml
  tags: scripts
- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: salsa.yml
  tags: salsa
- import_tasks: github.yml
  tags: github

- import_tasks: gnome.yml
  tags: gnome
