- import_tasks: apt.yml
  tags: apt
- import_tasks: brew.yml
  tags: brew
- import_tasks: snap.yml
  tags: snap
- import_tasks: printer.yml
  tags: printer

- import_tasks: keys.yml
  tags: keys
- import_tasks: scripts.yml
  tags: scripts
- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: salsa.yml
  tags: salsa
- import_tasks: github.yml
  tags: github

- import_tasks: dconf.yml
  tags: dconf
- import_tasks: tweaks.yml
  tags: tweaks
- import_tasks: extensions.yml
  tags: extensions
