# personalization
- import_tasks: apt.yml
  tags: apt
- import_tasks: fish.yml
  tags: fish
- import_tasks: scripts.yml
  tags: scripts
- import_tasks: dotfiles.yml
  tags: dotfiles
- import_tasks: dconf.yml
  tags: dconf

# brew
- import_tasks: brew.yml
  tags: brew

# ide
- import_tasks: code.yml
  tags: code
- import_tasks: intellij.yml
  tags: intellij

# printer
- import_tasks: printer.yml
  tags: printer

# work repositories
- import_tasks: salsa.yml
  tags: salsa
- import_tasks: github.yml
  tags: github

# development
- import_tasks: debian.yml
  tags: debian
- import_tasks: docker.yml
  tags: docker

# fun
- import_tasks: spotify.yml
  tags: spotify
