- name: install apt packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ apt_install_packages }}"

- name: purge apt packages
  become: yes
  apt:
    state: absent
    purge: yes
    autoremove: yes
    name: "{{ apt_purge_packages }}"
