- name: add i386 arch
  become: yes
  command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch

- name: install printer debs
  become: yes
  apt:
    deb: "{{ item }}"
  with_items:
    - http://www.brother.com/pub/bsc/linux/dlf/dcpj125lpr-1.1.3-1.i386.deb
    - http://www.brother.com/pub/bsc/linux/dlf/dcpj125cupswrapper-1.1.3-1.i386.deb
    - http://www.brother.com/pub/bsc/linux/dlf/brscan-skey-0.2.4-1.amd64.deb
    - http://www.brother.com/pub/bsc/linux/dlf/brscan3-0.2.11-5.amd64.deb
