- name: add i386 arch
  become: yes
  command: dpkg --add-architecture i386
  args:
    creates: /var/lib/dpkg/arch

- name: install printer debs
  become: yes
  apt:
    deb: "{{ item }}"
  with_items: "{{ printer_debs }}"
