- name: key spotify
  become: yes
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45

- name: repo spotify
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: install spotify
  become: yes
  apt:
    name: spotify-client
