- name: add brewed fish to shells
  become: yes
  lineinfile:
    path: /etc/shells
    line: "{{ brew }}/bin/fish"

- name: set fish as default shell
  become: yes
  user:
    name: "{{ user }}"
    shell: "{{ brew }}/bin/fish"

- name: add user to docker group
  become: yes
  user:
    name: "{{ user }}"
    append: yes
    groups:
      - docker

- name: disable bt on startup
  become: yes
  lineinfile:
    line: DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
    path: /etc/default/tlp
