- name: key code
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: repo code
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode # postinst script installs this file if does not exist

- name: install code
  become: yes
  apt:
    name: code
