- name: install nginx
  become: yes
  apt:
    update_cache: yes
    name: nginx
  notify: restart nginx

- name: copy nginx config
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: copy html index
  become: yes
  copy:
    src: index.html
    dest: /etc/nginx/index.html
  notify: restart nginx

- name: start nginx
  become: yes
  systemd:
    name: nginx.service
    enabled: yes
    state: started