apt_install_packages:
  - cheese
  - chrome-gnome-shell
  - docker.io
  - evince
  - firefox
  - gimp
  - gnome-boxes
  - gnome-calculator
  - gnome-calendar
  - gnome-clocks
  - gnome-system-monitor
  - gnome-tweaks
  - gnome-weather
  - fonts-firacode
  - fonts-noto-color-emoji
  - gpick
  - inkscape
  - libreoffice-calc
  - libreoffice-gtk3
  - libreoffice-writer
  - octave
  - simple-scan
  - totem
  - transmission
  - vagrant
  - virtualbox
  - xsel
  - neovim
  - network-manager-openconnect
  - network-manager-openconnect-gnome
  - network-manager-openvpn
  - network-manager-openvpn-gnome
  - network-manager-pptp
  - network-manager-pptp-gnome
  - network-manager-vpnc
  - network-manager-vpnc-gnome
  - zlib1g-dev # needed by `brew audit` and friends
apt_purge_packages:
  - chromium-browser
  - gnome-software
  - gnome-shell-extension-desktop-icons
  - gnome-shell-extension-ubuntu-dock
  - snapd
  - ubuntu-software
apt_disable_services:
  - apt-daily-upgrade.service
  - apt-daily-upgrade.timer
  - apt-daily.service
  - apt-daily.timer