- name: add i386 arch
  become: yes
  command: dpkg --add-architecture i386

- name: install apt packages
  become: yes
  apt:
    update_cache: yes
    name: "{{ apt_packages }}"

- name: install debs
  become: yes
  apt:
    deb: "{{ item }}"
  with_items: "{{ deb_packages }}"

- name: add virtualbox repo and key
  become: yes
  block:
    - name: key virtualbox
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    - name: repo virtualbox
      apt_repository:
        repo: deb https://download.virtualbox.org/virtualbox/debian buster contrib
        state: present
    - name: install virtualbox
      apt:
        name: virtualbox-6.0

- name: add docker repo and key
  become: yes
  block:
    - name: key docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - name: repo docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
    - name: install docker
      apt:
        name: docker-ce
