- name: install apt packages
  become: yes
  apt:
    update_cache: yes
    name:
      - build-essential
      - curl
      - wget
      - ruby
      - gpg
      - git
      - ssh
      - fish
      - neovim
      - snapd
      - htop

- name: enable and start snapd
  become: yes
  systemd:
    name: snapd
    enabled: yes
    state: started

- name: install snap packages
  become: yes
  ignore_errors: yes # needs some kernel modules and it doesn't work in Docker
  snap:
    classic: yes
    name:
      - intellij-idea-ultimate
      - code

- name: install brew if isn't already there
  shell: |
    CI=true ruby -e "`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install`"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: install brew packages
  homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    update_homebrew: yes
    name:
      - go
      - bat
      - hub

- name: add spotify repo and key
  become: yes
  block:
    - name: key spotify
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    - name: repo spotify
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
    - name: install spotify
      apt:
        name:
          - spotify-client

- name: add virtualbox repo and key
  become: yes
  block:
    - name: key virtualbox
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    - name: repo virtualbox
      apt_repository:
        repo: deb https://download.virtualbox.org/virtualbox/debian buster contrib
        state: present
    - name: install virtualbox
      apt:
        name:
          - virtualbox-6.0

- name: add docker repo and key and install
  become: yes
  block:
    - name: key docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - name: repo docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
    - name: install docker
      apt:
        name:
          - docker-ce

- name: clone and deploy dotfiles
  block:
    - name: clone dotfiles
      git:
        repo: git@github.com:dawidd6/dotfiles.git
        dest: "{{ home }}/.dotfiles"
        accept_hostkey: yes
        bare: yes
        version: master
    - name: deploy dotfiles
      shell: |
        alias dotfiles="git --git-dir={{ home }}/.dotfiles --work-tree=$HOME"
        dotfiles config --local status.showUntrackedFiles no
        dotfiles checkout

- name: clone debian repositories
  git:
    repo: "git@salsa.debian.org:go-team/packages/{{ item }}.git"
    dest: "{{ home }}/salsa/{{ item }}"
    accept_hostkey: yes
    version: debian/sid
  with_items:
    - termshark
    - docui

- name: clone github repositories
  git:
    repo: "git@github.com:dawidd6/{{ item }}.git"
    dest: "{{ home }}/github/{{ item }}"
    accept_hostkey: yes
    version: master
  with_items:
    - deber

- name: set default shell for user
  become: yes
  user:
    name: "{{ user }}"
    shell: /usr/bin/fish
