- name: Add flathub remote
  community.general.flatpak_remote:
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    name: flathub

- name: Install flatpak packages
  community.general.flatpak:
    method: user
    name: "{{ item }}"
  loop: "{{ flatpak_install_packages }}"
