- name: key spotify
  become: yes
  apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg

- name: repo spotify
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify

- name: install spotify
  become: yes
  apt:
    name: spotify-client