- name: create brew base directories
  file:
    path: "{{ ansible_env.HOME }}/.brew/bin"
    state: directory

- name: clone brew repository
  git:
    repo: "https://github.com/Homebrew/brew"
    dest: "{{ ansible_env.HOME }}/.brew/Homebrew"
    update: no
    version: master

- name: create symlink to brew binary
  file:
    src: "{{ ansible_env.HOME }}/.brew/Homebrew/bin/brew"
    dest: "{{ ansible_env.HOME }}/.brew/bin/brew"
    state: link
  notify: brew update
