- name: Create homebrew base directories
  become: true
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}/bin"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Clone homebrew repository
  ansible.builtin.git:
    repo: https://github.com/Homebrew/brew
    dest: "{{ homebrew_prefix }}/Homebrew"
    update: false
    version: master

- name: Create symlink to brew binary
  ansible.builtin.file:
    src: "{{ homebrew_prefix }}/Homebrew/bin/brew"
    dest: "{{ homebrew_prefix }}/bin/brew"
    state: link
  notify: Update homebrew

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install brew packages
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
  ansible.builtin.shell: "ulimit -Sn 65535; {{ homebrew_prefix }}/bin/brew install {{ brew_install_packages | join(' ') }}"
  register: brew_install
  changed_when: '"Installing" in brew_install.stdout'
