- name: create brew base directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.brew/bin"
    state: directory

- name: clone brew repository
  ansible.builtin.git:
    repo: "https://github.com/Homebrew/brew"
    dest: "{{ ansible_env.HOME }}/.brew/Homebrew"
    update: false
    version: master

- name: create symlink to brew binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.brew/Homebrew/bin/brew"
    dest: "{{ ansible_env.HOME }}/.brew/bin/brew"
    state: link
  notify: update brew

- meta: flush_handlers

- name: install brew packages
  community.general.homebrew:
    update_homebrew: true
    path: "{{ ansible_env.HOME }}/.brew/bin"
    name:
      - dawidd6/tap/deber
      - dawidd6/tap/dh-make-golang
      - bat
      - diff-so-fancy
      - distrobox
      - gh
      - ghorg
      - gitbatch
      - ipcalc
      - jfrog-cli
      - jq
      - lab
      - neofetch
      - shellcheck
