- name: Create homebrew base directories
  become: true
  ansible.builtin.file:
    path: "{{ prefix }}/bin"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Clone homebrew repository
  ansible.builtin.git:
    repo: https://github.com/Homebrew/brew
    dest: "{{ prefix }}/Homebrew"
    update: false
    version: master

- name: Create symlink to brew binary
  ansible.builtin.file:
    src: "{{ prefix }}/Homebrew/bin/brew"
    dest: "{{ prefix }}/bin/brew"
    state: link
  notify: Update homebrew

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install brewed tools
  community.general.homebrew:
    path: "{{ prefix }}/bin"
    name:
      - dawidd6/tap/deber
      - dawidd6/tap/dh-make-golang
      - ansible
      - ansible-lint
      - bat
      - curl
      - diff-so-fancy
      - diffoscope
      - distrobox
      - docker-completion
      - fish
      - fzf
      - gh
      - ghorg
      - git
      - gitbatch
      - go
      - htop
      - ipcalc
      - jfrog-cli
      - jq
      - lab
      - lm-sensors
      - ncdu
      - neofetch
      - neovim
      - nmap
      - node
      - parallel
      - python
      - ruby
      - shellcheck
      - trash-cli
      - tree
      - xsel
