- name: create brew base directories
  file:
    path: "{{ ansible_env.HOME }}/.brew/bin"
    state: directory

- name: clone brew repository
  git:
    repo: "https://github.com/Homebrew/brew"
    dest: "{{ ansible_env.HOME }}/.brew/Homebrew"
    update: no
    version: master

- name: create symlink to brew binary
  file:
    src: "{{ ansible_env.HOME }}/.brew/Homebrew/bin/brew"
    dest: "{{ ansible_env.HOME }}/.brew/bin/brew"
    state: link
  notify: update brew

- meta: flush_handlers

- name: install brew packages
  homebrew:
    update_homebrew: yes
    path: "{{ ansible_env.HOME }}/.brew/bin"
    name:
      - dawidd6/tap/deber
      - dawidd6/tap/dh-make-golang
      - bat
      - curl
      - diff-so-fancy
      - diffoscope
      - fzf
      - gh
      - ghorg
      - git
      - gitbatch
      - go
      - hub
      - ipcalc
      - jfrog-cli
      - jq
      - lab
      - lazygit
      - lm-sensors
      - ncdu
      - neofetch
      - neovim
      - nmap
      - packer
      - parallel
      - ruby
      - shellcheck
      - trash-cli
      - tree
      - xsel
