- name: Update homebrew
  ansible.builtin.command: "{{ homebrew_prefix }}/bin/brew update -f"

- name: Install nvim plugins
  environment:
    PATH: "{{ homebrew_prefix }}/bin"
  ansible.builtin.command: nvim -c PlugInstall -c qa

- name: Checkout dotfiles
  ansible.builtin.command: "git --git-dir={{ ansible_env.HOME }}/.dotfiles --work-tree={{ ansible_env.HOME }} checkout -f"
  args:
    warn: false

- name: Checkout keys
  ansible.builtin.command: "git --git-dir={{ ansible_env.HOME }}/.keys --work-tree={{ ansible_env.HOME }} checkout -f"
  args:
    warn: false

- name: Start tlp
  become: true
  ansible.builtin.command: tlp start
