- name: Deploy dotfiles
  block:
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: https://github.com/dawidd6/dotfiles.git
        dest: "{{ ansible_env.HOME }}/.dotfiles"
        update: false
        bare: true
        version: master
      notify: Checkout dotfiles

    - name: Do not show untracked dotfiles
      community.general.git_config:
        repo: "{{ ansible_env.HOME }}/.dotfiles"
        name: "status.showUntrackedFiles"
        value: "no"
        scope: local

    - name: Set dotfiles fetch config
      community.general.git_config:
        repo: "{{ ansible_env.HOME }}/.dotfiles"
        name: "remote.origin.fetch"
        value: "+refs/heads/*:refs/remotes/origin/*"
        scope: local

- name: Deploy keys
  block:
    - name: Lookup keys
      ansible.builtin.find:
        file_type: directory
        paths:
          - "/media"
        depth: 3
        recurse: true
        patterns: "*keys"
      register: keys_dir

    - name: Deploy keys
      when: keys_dir.matched == 1
      block:
        - name: Clone keys
          ansible.builtin.git:
            repo: "{{ keys_dir.files[0].path }}"
            dest: "{{ ansible_env.HOME }}/.keys"
            accept_hostkey: true
            bare: true
            version: master
          notify: Checkout keys

        - name: Set configs
          community.general.git_config:
            repo: "{{ ansible_env.HOME }}/.keys"
            name: "{{ item.key }}"
            value: "{{ item.value }}"
            scope: local
          with_items:
            - key: status.showUntrackedFiles
              value: false
            - key: remote.origin.fetch
              value: +refs/heads/*:refs/remotes/origin/*

        - name: Fix keys permissions
          ansible.builtin.file:
            path: "{{ item }}"
            mode: 0600
          with_fileglob:
            - "{{ ansible_env.HOME }}/.gnupg/*"
            - "{{ ansible_env.HOME }}/.ssh/*"


- name: Deploy scripts
  ansible.builtin.git:
    repo: https://github.com/dawidd6/bin.git
    dest: "{{ ansible_env.HOME }}/bin"
    update: false
    version: master
