- name: create brew base directories
  file:
    path: "{{ brew }}/bin"
    state: directory

- name: clone brew repository
  git:
    repo: "https://github.com/Homebrew/brew"
    dest: "{{ brew }}/Homebrew"
    update: no
    version: "master"

- name: create symlink to brew binary
  file:
    src: "{{ brew }}/Homebrew/bin/brew"
    dest: "{{ brew }}/bin/brew"
    state: "link"
  notify: brew update
