- name: Install programming langs
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name:
      - go
      - node
      - python
      - ruby

- name: Install tools from my tap
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name:
      - dawidd6/tap/deber
      - dawidd6/tap/dh-make-golang

- name: Install other tools
  environment:
    HOMEBREW_NO_AUTO_UPDATE: 1
  ansible.builtin.command: "/home/linuxbrew/.linuxbrew/bin/brew install {{ formulae | join(' ') }}"
  register: brew_install
  changed_when: '"Installing" in brew_install.stdout'
  vars:
    formulae:
      - bat
      - diff-so-fancy
      - diffoscope
      - distrobox
      - fzf
      - gh
      - ghorg
      - gitbatch
      - htop
      - ipcalc
      - jfrog-cli
      - jq
      - lab
      - lm-sensors
      - ncdu
      - neofetch
      - neovim
      - nmap
      - parallel
      - shellcheck
      - trash-cli
      - tree
      - xsel
