- name: install tlp
  become: yes
  apt:
    name: tlp
  notify: start tlp

- name: disable bt on startup
  become: yes
  lineinfile:
    line: DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
    path: /etc/tlp.d/99-no-bluetooth-at-startup.conf
    create: yes
    mode: 0644
