- name: lookup keys
  find:
    file_type: directory
    paths:
      - "/media"
    depth: 3
    recurse: yes
    patterns: "*keys"
  register: keys_dir

- name: debug
  debug:
    var: keys_dir.files

- name: deploy keys
  when: keys_dir.matched == 1
  block:
    - name: clone keys
      git:
        repo: "{{ keys_dir.files[0].path }}"
        dest: "{{ ansible_env.HOME }}/.keys"
        accept_hostkey: yes
        bare: yes
        version: master
      notify: checkout keys

    - name: set configs
      git_config:
        repo: "{{ ansible_env.HOME }}/.keys"
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: local
      with_items:
        - key: status.showUntrackedFiles
          value: no
        - key: remote.origin.fetch
          value: +refs/heads/*:refs/remotes/origin/*

    - name: fix keys permissions
      file:
        path: "{{ item }}"
        mode: 0600
      with_fileglob:
        - "{{ ansible_env.HOME }}/.gnupg/*"
        - "{{ ansible_env.HOME }}/.ssh/*"
