- name: lookup keys
  find:
    file_type: directory
    paths:
      - "{{ '/Volumes' if ansible_facts['os_family'] == 'Darwin' else '/media' }}"
    depth: 3
    recurse: yes
    patterns: "*keys"
  register: keys_dir

- name: debug
  debug:
    var: keys_dir.files

- name: deploy keys
  when: keys_dir.matched == 1
  block:
    - name: clone keys
      git:
        repo: "{{ keys_dir.files[0].path }}"
        dest: "{{ keys }}"
        accept_hostkey: yes
        bare: yes
        version: master
    - name: do not show untracked keys
      git_config:
        repo: "{{ keys }}"
        name: "status.showUntrackedFiles"
        value: "no"
        scope: local
    - name: set keys fetch config
      git_config:
        repo: "{{ keys }}"
        name: "remote.origin.fetch"
        value: "+refs/heads/*:refs/remotes/origin/*"
        scope: local
    - name: checkout keys
      command: git --git-dir="{{ keys }}" --work-tree="{{ ansible_env.HOME }}" checkout -f
      args:
        creates: "{{ ansible_env.HOME }}/.the_codes"
        warn: false
    - name: fix keys permissions
      file:
        path: "{{ item }}"
        mode: 0600
      with_fileglob:
        - "{{ ansible_env.HOME }}/.gnupg/*"
        - "{{ ansible_env.HOME }}/.ssh/*"
