- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
      - zlib1g-dev # for brew style

- name: Create brew base directories
  become: true
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew/bin
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: Clone brew repository
  ansible.builtin.git:
    repo: https://github.com/Homebrew/brew
    dest: /home/linuxbrew/.linuxbrew/Homebrew
    update: false
    version: master

- name: Create symlink to brew binary
  ansible.builtin.file:
    src: /home/linuxbrew/.linuxbrew/Homebrew/bin/brew
    dest: /home/linuxbrew/.linuxbrew/bin/brew
    state: link
  notify: Update brew

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
