- name: Install fish
  community.general.homebrew:
    path: /home/linuxbrew/.linuxbrew/bin
    name: fish

- name: Set fish as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /home/linuxbrew/.linuxbrew/bin/fish
