- name: Install fish
  community.general.homebrew:
    path: "{{ homebrew_prefix }}/bin"
    name: fish

- name: Set fish as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ homebrew_prefix }}/bin/fish"
