- name: Install nvim
  community.general.homebrew:
    path: "{{ homebrew_prefix }}/bin"
    name: neovim

- name: Create nvim directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory
    mode: 0775

- name: Install nvim plugin manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0775
  notify: Install nvim plugins
